# Generated by Django 2.0.1 on 2018-05-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haircut', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='comment',
            new_name='barber_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='customer_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
